# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog Template
# url: http://litaotao.github.io
url: https://phoneTalent.github.io
feed: /atom.xml
author_info: <a href="http://phoneTalent.github.io/">gaozhichao</a>

myblog:
  gavatar: images/2.jpg
  gpname: gaozhichao
  linkedin: http://www.linkedin.com/in/taotaoli
  github: https://github.com/GaoZhiChaoChina
  email: mailto:taotao.engineer@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
